config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  
  get 'about', to: 'pages#about'

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  validates :title, presence: true, length: { minimum: 3, maximun: 50}
  validates :description, presence: true, length: { minimum: 10, maximun: 300}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  
  end
  
  def about
  
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Alpha Blog</title>

    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag '/assets/stylesheets/bootstrap.min.css' %>
    <%= stylesheet_link_tag '/assets/stylesheets/cover.css' %>

  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Alpha Blog</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li><%= link_to 'Home', root_path %></li>
                  <li><a href="#"><%= link_to 'About', about_path %></a></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <div class="row">
              <div class="col-lg-6">
                <div class="profile-inner">
                  <%= image_tag 'http://f.ptcdn.info/384/038/000/nzgq53mgrXtRM7HEG7B-o.png', :class => "icon-profile" %>  
                </div>
              </div>
              <div class="col-lg-6 about-me">
                <h2 class="about-title">About Me</h2>
                <p class="about-content">Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
              </div>
            </div>
          </div>

        </div>

      </div>

    </div>
    
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Alpha Blog</title>

    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag '/assets/stylesheets/bootstrap.min.css' %>
    <%= stylesheet_link_tag '/assets/stylesheets/cover.css' %>

  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Alpha Blog</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li><%= link_to 'Home', root_path %></li>
                  <li><a href="#"><%= link_to 'About', about_path %></a></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">Welcome to Alpha Blog</h1>
            <p class="lead">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            <p class="lead">
              <%= link_to 'Learn more about me', about_path, :class => 'btn btn-lg btn-default' %>
            </p>
          </div>

        </div>

      </div>

    </div>
    
  </body>
</html>